"""harvester_records_table

Revision ID: 2ccc7651e959
Revises: 6bfebb4af6ba
Create Date: 2023-02-08 16:19:29.622107

"""
import sqlalchemy as sa
from alembic import op
from SciXPipelineUtils.scix_uuid import scix_uuid as uuid
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2ccc7651e959"
down_revision = "6bfebb4af6ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "harvester_records",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            default=uuid.uuid7,
            nullable=False,
        ),
        sa.Column("s3_key", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("ARXIV", "APS", "AAS", "MNRAS", "PNAAS", name="source"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("harvester_records")
    sa.Enum("ARXIV", "APS", "AAS", "MNRAS", "PNAAS", name="source").drop(op.get_bind())
    # ### end Alembic commands ###
